---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app netbox
  namespace: flux-system
spec:
  targetNamespace: infra
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./openshift/apps/infra/netbox/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: ocp-neptune
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
