---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: automation-gateway-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: automation-gateway-postgres-secret
    template:
      engineVersion: v2
      data:
        database: "{{ .DATABASE }}"
        host: postgres-rw.database.svc.cluster.local
        password: "{{ .POSTGRES_PASS }}"
        port: "5432"
        secret_key: "{{ .SECRET_KEY }}"
        type: unmanaged
        username: "{{ .POSTGRES_USER }}"
  dataFrom:
    - extract:
        key: automation-gateway
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: admin-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: admin-password-secret
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: automation-gateway
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: automation-controller-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: automation-controller-postgres-secret
    template:
      engineVersion: v2
      data:
        database: "{{ .DATABASE }}"
        host: postgres-rw.database.svc.cluster.local
        password: "{{ .POSTGRES_PASS }}"
        port: "5432"
        secret_key: "{{ .SECRET_KEY }}"
        type: unmanaged
        username: "{{ .POSTGRES_USER }}"
  dataFrom:
    - extract:
        key: automation-controller
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eda-controller-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: eda-controller-postgres-secret
    template:
      engineVersion: v2
      data:
        database: "{{ .DATABASE }}"
        host: postgres-rw.database.svc.cluster.local
        password: "{{ .POSTGRES_PASS }}"
        port: "5432"
        secret_key: "{{ .SECRET_KEY }}"
        type: unmanaged
        username: "{{ .POSTGRES_USER }}"
  dataFrom:
    - extract:
        key: eda-controller
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: automation-hub-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: automation-hub-postgres-secret
    template:
      engineVersion: v2
      data:
        database: "{{ .DATABASE }}"
        host: postgres-rw.database.svc.cluster.local
        password: "{{ .POSTGRES_PASS }}"
        port: "5432"
        database_fields.symmetric.key: "{{ .SECRET_KEY }}"
        type: unmanaged
        username: "{{ .POSTGRES_USER }}"
  dataFrom:
    - extract:
        key: automation-hub
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: automation-hub-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: automation-hub-s3-secret
    template:
      engineVersion: v2
      data:
        s3-access-key-id: "{{ .SECRET_MINIO_ACCESS_KEY }}"
        s3-bucket-name: "automation-hub"
        s3-endpoint: "{{ .SECRET_MINIO_ENDPOINT }}"
        s3-region: "us-east-1"
        s3-secret-access-key: "{{ .SECRET_MINIO_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: automation-hub
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chatbot-configuration
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: chatbot-configuration-secret
    template:
      engineVersion: v2
      data:
        chatbot_model: "{{ .CHATBOT_MODEL }}"
        chatbot_url: "{{ .CHATBOT_URL }}"
        chatbot_token: "{{ .CHATBOT_TOKEN }}"
        chatbot_llm_provider_type: "openai"
        aap_gateway_url: "http://demo"
        aap_controller_url: "http://demo-controller-service"
  dataFrom:
    - extract:
        key: automation-chatbot
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chatbot-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: chatbot-postgres-secret
    template:
      engineVersion: v2
      data:
        database: "{{ .DATABASE }}"
        host: postgres-rw.database.svc.cluster.local
        password: "{{ .POSTGRES_PASS }}"
        port: "5432"
        secret_key: "{{ .SECRET_KEY }}"
        type: unmanaged
        username: "{{ .POSTGRES_USER }}"
  dataFrom:
    - extract:
        key: automation-chatbot
