---
# yaml-language-server: $schema=https://raw.githubusercontent.com/hashicorp/vault-helm/main/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: vault
      version: 0.29.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      enabled: false
      openshift: true
    server:
      enabled: true
      image:
        repository: "docker.io/hashicorp/vault"
        tag: "1.19.5"
      updateStrategyType: RollingUpdate
      readinessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
      dataStorage:
        enabled: true
        size: 20Gi
        mountPath: "/vault/data"
        accessMode: ReadWriteOnce
      extraSecretEnvironmentVars:
        - envName: AWS_ACCESS_KEY_ID
          secretName: vault-secret
          secretKey: AWS_ACCESS_KEY_ID
        - envName: AWS_SECRET_ACCESS_KEY
          secretName: vault-secret
          secretKey: AWS_SECRET_ACCESS_KEY
        - envName: VAULT_AWSKMS_SEAL_KEY_ID
          secretName: vault-secret
          secretKey: VAULT_AWSKMS_SEAL_KEY_ID
      extraEnvironmentVars:
        TZ: ${TIMEZONE}
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi
      standalone:
        enabled: true
        config: |
          log_format = "json"
          log_level = "debug"
          ui = true
          cluster_name = "vault"
          seal "awskms" {
            region = "us-east-1"
          }
          storage "file" {
            path = "/vault/data"
          }
          # HTTPS listener
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_disable = 1
          }
          telemetry {
            prometheus_retention_time = "24h"
            disable_hostname = true
          }
