---
apiVersion: v1
kind: Node
metadata:
  name: neptune02.ocp.home.arpa
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    cluster.ocs.openshift.io/openshift-storage: ""
    kubernetes.io/hostname: neptune02
    node.ocs.openshift.io/storage: "true"
