---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ocp-neptune
  namespace: flux-system
spec:
  interval: 30m
  url: ssh://git@github.com/ario-labs/ocp-neptune
  ref:
    branch: main
  secretRef:
    name: github-deploy-key
  ignore: |
    # exclude all
    /*
    # include dirs
    !/openshift
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./openshift/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: ocp-neptune
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - name: cluster-settings
        kind: ConfigMap
        optional: true
      - name: cluster-secrets
        kind: Secret
        optional: true
