---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netbox
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: netbox-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        db_password: "{{ .POSTGRES_PASS }}"
        superuser_password: "{{ .password }}"
        superuser_api_token: "{{ .API_KEY }}"
        secret_key: "{{ .SECRET_KEY }}"
        email_password: ""
        napalm_password: ""
        redis_tasks_password: ""
        redis_cache_password: ""

        NETBOX_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        NETBOX_POSTGRES_PORT: "5432"
        NETBOX_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        NETBOX_POSTGRES_DB: netbox
        SECRET_S3_ACCESS_KEY: "{{ .S3_ACCESS_KEY }}"
        SECRET_S3_SECRET_KEY: "{{ .S3_SECRET_KEY }}"
        AWS_S3_ENDPOINT_URL: "{{ .S3_ENDPOINT_URL }}"
        SECRET_DOMAIN: "${SECRET_DOMAIN}"
  dataFrom:
    - extract:
        key: netbox
