---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: netbox-route
spec:
  host: "netbox.${SECRET_DOMAIN}"
  to:
    kind: Service
    name: netbox
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
